* Abstract

Neural network architectures with algorithmic tasks are known to show late generalisation after a long period of overfitting. We study that phenomenon by feeding the transformer a Fibonacci modulo sequence. We aimed to analyse this pattern using mechanistic interpretability and better understand it. We identified that the model seems to generalise after prolonged overfitting, that the mathematical nature of the Pisano period causes a data leak in the Fibonacci modulo, and that this affects the training and evaluation of the transformer. We also analysed and experimented with the transformer model by disassembling its different components to see if late generalisation still occurs. Our study concludes the behaviour of the transformer on types of algorithmic tasks like Fibonacci modulo and modular addition, and how different components of a transformer architecture contribute to such behaviour.


** Introduction

Neural network architecture exhibits a phenomenon commonly known as grokking after a long period of overfitting. This effect is commonly caused in an algorithmic task in which the model can learn to generalise instead of memorising the problem. In our study, we analyse different types of problem sets like Fibonacci Modulo along with modular addition. The periodic mathematical nature of the Fibonacci modulo problem causes a natural data leak due to the Pisano period, where modular addition tasks are straightforward when feeding the transformer model with seen and unseen pairs in training and evaluation sets. We also experiment with different components of a transformer architecture to analyse the contrubition on grokking.
